window.docContents[130].resolve({"/#PSBP-Documentation--Programming-With-Failure--ProgramWithValidation":{"id":"/#PSBP-Documentation--Programming-With-Failure--ProgramWithValidation","header":"10.8. ProgramWithValidation","context":"PSBP Documentation\u0009Programming With Failure","contents":"abbrev ProgramWithValidation ε computation :=\n  FromComputationValuedFunction (FailureT ε computation)\n\ndef materializeWithValidation\n    [Monad computation]\n    [Monoid ε] {α β : Type} :\n  ProgramWithValidation ε computation α β →\n  α →\n  computation (ε ⊕ β) :=\n    λ ⟨αftεcβ⟩ α =>\n      (αftεcβ α).toComputationOfSum\n\ndef materializeActiveWithValidation\n    [Monoid ε] {α β : Type} :\n ProgramWithValidation ε Active α β → α → (ε ⊕ β) :=\n  materializeWithValidation\n\n\ninstance Functor (FailureT ε computation), instance Applicative (FailureT ε computation) and\nmaterializeActiveWithValidation above cause programs to accumulate all exceptions that are encountered.\n\nThe examples below illustrate this accumulation behavior.\n\n"}});